db_name: employee_db
db_user: db_user
#db_password: Passw0rd
#paste vault encrpyted variable below
db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35376561353661333135626630666366323963353461313833646431383132663364633265643461
          6238616530383439386535356537323266313163306434660a396161336236383135333162333363
          62316530336563363761383030666339313337393733323036373565353363613866373361623130
          3864633933643833340a396464653163663434663733663066323864373464316438353430633433
          3838
